# Install the pre-commit hooks below with
# 'pre-commit install'

# Auto-update the version of the hooks with
# 'pre-commit autoupdate'

# Run the hooks on all files with
# 'pre-commit run --all'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
        files: (renderer/|examples/|test_resources/tests/).*.py$
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: debug-statements
        files: (renderer/|examples/|test_resources/tests/).*.py$
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        files: (renderer/|examples/|test_resources/tests/)*.py$
        args: [--remove]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: no-commit-to-branch
        args: [--branch=master]
      - id: trailing-whitespace
        files: (renderer/|examples/|test_resources/tests/).*.py$

  - repo: https://github.com/PyCQA/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        files: (renderer/|examples/|test_resources/tests/).*.py$
        args:
          [
            --only-modified,
            --combine-star,
            --order-by-type,
            --use-parentheses,
            --case-sensitive,
            --force-sort-within-sections,
          ]

  - repo: https://github.com/psf/black
    # The `refs/tags/<tag>:refs/tags/<tag>` is needed for black's required-version to work:
    # https://github.com/psf/black/issues/2493#issuecomment-1081987650
    rev: "refs/tags/23.7.0:refs/tags/23.7.0"
    hooks:
      - id: black
        files: (renderer/|examples/|test_resources/tests/).*.py$
        language_version: python3.11

  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: "1.3.1"
    hooks:
      - id: tox-ini-fmt

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: "v6.31.0"
    hooks:
      - id: cspell
        exclude: (\.gitignore|tests/.*|\.pre-commit-config\.yaml|\.pyi|\.style\.yapf|tox\.ini)$
        args:
          [
            --unique,
            --cache,
            --no-must-find-files,
            --no-progress,
            --no-summary,
            --gitignore,
          ]
