# Install the pre-commit hooks below with
# 'pre-commit install'

# Auto-update the version of the hooks with
# 'pre-commit autoupdate'

# Run the hooks on all files with
# 'pre-commit run --all'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
        files: (renderer/|examples/|test_resources/tests/).*.py$
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: debug-statements
        files: (renderer/|examples/|test_resources/tests/).*.py$
      - id: destroyed-symlinks
      - id: end-of-file-fixer
        exclude: \.ipynb$
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: no-commit-to-branch
        args: [--branch=master]
      - id: trailing-whitespace
        files: (renderer/|examples/|test_resources/tests/).*.py$

  - repo: local
    hooks:
      - id: ruff-imports
        name: Ruff import sorting
        entry: uv run --no-sync ruff check --select I --fix
        language: system
        files: ^(assets/|renderer/|examples/|test_resources/|tests/|tools/).*[.]pyi?$

      - id: ruff-check
        name: Ruff lint
        entry: uv run --no-sync ruff check
        language: system
        files: ^(assets/|renderer/|examples/|test_resources/|tests/|tools/).*[.]pyi?$

      - id: ruff-format
        name: Ruff format
        entry: uv run --no-sync ruff format
        language: system
        files: ^(assets/|renderer/|examples/|test_resources/|tests/|tools/).*[.]pyi?$

      - id: pyright
        name: pyright
        entry: uv run --no-sync pyright
        language: system
        types: [python]
        files: (renderer/|examples/|test_resources/tests/).*.py$
        pass_filenames: false
        stages: [manual]

      - id: cspell
        name: cspell
        entry: cspell-cli
        language: node
        additional_dependencies: [cspell-cli@10.0.1]
        types: [text]
        exclude: (\.gitignore|tests/.*|notebooks/.*\.ipynb$|\.pre-commit-config\.yaml|\.pyi|\.style\.yapf|tox\.ini)$
        args:
          [
            --no-must-find-files,
            --no-progress,
            --no-summary,
            --gitignore,
            --unique,
            --files,
          ]

  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: "1.6.0"
    hooks:
      - id: tox-ini-fmt
