# Install the pre-commit hooks below with
# 'pre-commit install'

# Auto-update the version of the hooks with
# 'pre-commit autoupdate'

# Run the hooks on all files with
# 'pre-commit run --all'

repos:
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: "v6.31.0"
    hooks:
      - id: cspell
        exclude: (\.gitignore|tests/.*|\.pre-commit-config\.yaml|\.pyi|\.style\.yapf|tox\.ini)$
        args:
          [
            --unique,
            --cache,
            --no-must-find-files,
            --no-progress,
            --no-summary,
            --gitignore,
          ]
