$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
language: en-gb
ignorePaths:
  - .github/**/*
  - .gitignore
  - .pre-commit-config.yaml
  - .style.yapf
  - cspell.config.yaml
  - tox.ini
dictionaryDefinitions: []
dictionaries:
  - en-gb
words:
  - addopts
  - arange
  - argmax
  - argmin
  - argnames
  - argnums
  - astype
  - axises
  - blit
  - brax
  - capsulex
  - capsuley
  - capsulez
  - capx
  - capy
  - capz
  - centering
  - checkify
  - coef
  - Colab
  - cumsum
  - dataclass
  - dataclasses
  - diag
  - Dtype
  - dtypes
  - erwincoumans
  - EUROGRAPHICS
  - figsize
  - finfo
  - fori
  - fovy
  - Frag
  - framebuffer
  - getpixel
  - GLSL
  - Gouraud
  - hfov
  - Hodgman
  - Hongyu
  - HWWS
  - iinfo
  - importlib
  - imsave
  - imshow
  - Indicess
  - isort
  - issubdtype
  - jaxlib
  - jaxrenderer
  - jaxtyped
  - jaxtyping
  - jitted
  - keepdims
  - linalg
  - lowerbound
  - matplotlib
  - mimage
  - mpimg
  - ncols
  - ndim
  - nfaces
  - NOPERSPECTIVE
  - nrows
  - numpy
  - nverts
  - Olano
  - phong
  - postprocessing
  - pregenerated
  - PRNG
  - pycache
  - pypi
  - pyplot
  - pyproject
  - pyright
  - pytest
  - pytinyrenderer
  - qualname
  - quat
  - sharex
  - sharey
  - staticmethod
  - swapaxes
  - Teng
  - tinyrenderer
  - Trey
  - varyings
  - vfov
  - vmap
  - zbuffer
  - zbuffers
ignoreWords: []
import: []
