[tox]
requires =
    tox>=4.2
    tox-uv>=1.29
env_list =
    lint
    py{314, 313, 312, 311, 310, 39}

[testenv]
runner = uv-venv-lock-runner
description = run unit tests
dependency_groups =
    dev
    test
commands =
    pytest tests/ --import-mode importlib

[testenv:lint]
runner = uv-venv-lock-runner
description = run linters
dependency_groups =
    dev
commands =
    ruff check --select I {posargs:assets renderer examples test_resources tests tools}
    ruff format --check {posargs:assets renderer examples test_resources tests tools}
