[tox]
requires =
    tox>=4.64.5
    tox-uv>=1.36
env_list =
    lint
    py{314, 313, 312}

[testenv]
runner = uv-venv-lock-runner
description = run unit tests
commands =
    pytest tests/ --import-mode importlib
dependency_groups =
    dev
    test

[testenv:lint]
runner = uv-venv-lock-runner
description = run linters
commands =
    ruff check --select I {posargs:assets renderer examples test_resources tests tools}
    ruff format --check {posargs:assets renderer examples test_resources tests tools}
dependency_groups =
    dev
