"""
This type stub file was generated by pyright.
"""

from . import _api, _docstring

"""
GUI neutral widgets
===================

Widgets that are designed to work for any of the GUI backends.
All of these widgets require you to predefine a `matplotlib.axes.Axes`
instance and pass that as the first parameter.  Matplotlib doesn't try to
be too smart with respect to layout -- you will have to figure out how
wide and tall you want your Axes to be to accommodate your widget.
"""

class LockDraw:
    """
    Some widgets, like the cursor, draw onto the canvas, and this is not
    desirable under all circumstances, like when the toolbar is in zoom-to-rect
    mode and drawing a rectangle.  To avoid this, a widget can acquire a
    canvas' lock with ``canvas.widgetlock(widget)`` before drawing on the
    canvas; this will prevent other widgets from doing so at the same time (if
    they also try to acquire the lock first).
    """

    def __init__(self) -> None: ...
    def __call__(self, o):  # -> None:
        """Reserve the lock for *o*."""
        ...
    def release(self, o):  # -> None:
        """Release the lock from *o*."""
        ...
    def available(self, o):  # -> bool:
        """Return whether drawing is available to *o*."""
        ...
    def isowner(self, o):  # -> bool:
        """Return whether *o* owns this lock."""
        ...
    def locked(self):  # -> bool:
        """Return whether the lock is currently held by an owner."""
        ...

class Widget:
    """
    Abstract base class for GUI neutral widgets.
    """

    drawon = ...
    eventson = ...
    _active = ...
    def set_active(self, active):  # -> None:
        """Set whether the widget is active."""
        ...
    def get_active(self):  # -> bool:
        """Get whether the widget is active."""
        ...
    active = ...
    def ignore(self, event):  # -> bool:
        """
        Return whether *event* should be ignored.

        This method should be called at the beginning of any event callback.
        """
        ...

class AxesWidget(Widget):
    """
    Widget connected to a single `~matplotlib.axes.Axes`.

    To guarantee that the widget remains responsive and not garbage-collected,
    a reference to the object should be maintained by the user.

    This is necessary because the callback registry
    maintains only weak-refs to the functions, which are member
    functions of the widget.  If there are no references to the widget
    object it may be garbage collected which will disconnect the callbacks.

    Attributes
    ----------
    ax : `~matplotlib.axes.Axes`
        The parent Axes for the widget.
    canvas : `~matplotlib.backend_bases.FigureCanvasBase`
        The parent figure canvas for the widget.
    active : bool
        If False, the widget does not respond to events.
    """

    def __init__(self, ax) -> None: ...
    def connect_event(self, event, callback):  # -> None:
        """
        Connect a callback function with an event.

        This should be used in lieu of ``figure.canvas.mpl_connect`` since this
        function stores callback ids for later clean up.
        """
        ...
    def disconnect_events(self):  # -> None:
        """Disconnect all events created by this widget."""
        ...

class Button(AxesWidget):
    """
    A GUI neutral button.

    For the button to remain responsive you must keep a reference to it.
    Call `.on_clicked` to connect to the button.

    Attributes
    ----------
    ax
        The `matplotlib.axes.Axes` the button renders into.
    label
        A `matplotlib.text.Text` instance.
    color
        The color of the button when not hovering.
    hovercolor
        The color of the button when hovering.
    """

    def __init__(
        self, ax, label, image=..., color=..., hovercolor=..., *, useblit=...
    ) -> None:
        """
        Parameters
        ----------
        ax : `~matplotlib.axes.Axes`
            The `~.axes.Axes` instance the button will be placed into.
        label : str
            The button text.
        image : array-like or PIL Image
            The image to place in the button, if not *None*.  The parameter is
            directly forwarded to `~matplotlib.axes.Axes.imshow`.
        color : color
            The color of the button when not activated.
        hovercolor : color
            The color of the button when the mouse is over it.
        useblit : bool, default: True
            Use blitting for faster drawing if supported by the backend.
            See the tutorial :doc:`/tutorials/advanced/blitting` for details.

            .. versionadded:: 3.7
        """
        ...
    def on_clicked(self, func):  # -> int:
        """
        Connect the callback function *func* to button click events.

        Returns a connection id, which can be used to disconnect the callback.
        """
        ...
    def disconnect(self, cid):  # -> None:
        """Remove the callback function with connection id *cid*."""
        ...

class SliderBase(AxesWidget):
    """
    The base class for constructing Slider widgets. Not intended for direct
    usage.

    For the slider to remain responsive you must maintain a reference to it.
    """

    def __init__(
        self,
        ax,
        orientation,
        closedmin,
        closedmax,
        valmin,
        valmax,
        valfmt,
        dragging,
        valstep,
    ) -> None: ...
    def disconnect(self, cid):  # -> None:
        """
        Remove the observer with connection id *cid*.

        Parameters
        ----------
        cid : int
            Connection id of the observer to be removed.
        """
        ...
    def reset(self):  # -> None:
        """Reset the slider to the initial value."""
        ...

class Slider(SliderBase):
    """
    A slider representing a floating point range.

    Create a slider from *valmin* to *valmax* in Axes *ax*. For the slider to
    remain responsive you must maintain a reference to it. Call
    :meth:`on_changed` to connect to the slider event.

    Attributes
    ----------
    val : float
        Slider value.
    """

    @_api.make_keyword_only("3.7", name="valinit")
    def __init__(
        self,
        ax,
        label,
        valmin,
        valmax,
        valinit=...,
        valfmt=...,
        closedmin=...,
        closedmax=...,
        slidermin=...,
        slidermax=...,
        dragging=...,
        valstep=...,
        orientation=...,
        *,
        initcolor=...,
        track_color=...,
        handle_style=...,
        **kwargs
    ) -> None:
        """
        Parameters
        ----------
        ax : Axes
            The Axes to put the slider in.

        label : str
            Slider label.

        valmin : float
            The minimum value of the slider.

        valmax : float
            The maximum value of the slider.

        valinit : float, default: 0.5
            The slider initial position.

        valfmt : str, default: None
            %-format string used to format the slider value.  If None, a
            `.ScalarFormatter` is used instead.

        closedmin : bool, default: True
            Whether the slider interval is closed on the bottom.

        closedmax : bool, default: True
            Whether the slider interval is closed on the top.

        slidermin : Slider, default: None
            Do not allow the current slider to have a value less than
            the value of the Slider *slidermin*.

        slidermax : Slider, default: None
            Do not allow the current slider to have a value greater than
            the value of the Slider *slidermax*.

        dragging : bool, default: True
            If True the slider can be dragged by the mouse.

        valstep : float or array-like, default: None
            If a float, the slider will snap to multiples of *valstep*.
            If an array the slider will snap to the values in the array.

        orientation : {'horizontal', 'vertical'}, default: 'horizontal'
            The orientation of the slider.

        initcolor : color, default: 'r'
            The color of the line at the *valinit* position. Set to ``'none'``
            for no line.

        track_color : color, default: 'lightgrey'
            The color of the background track. The track is accessible for
            further styling via the *track* attribute.

        handle_style : dict
            Properties of the slider handle. Default values are

            ========= ===== ======= ========================================
            Key       Value Default Description
            ========= ===== ======= ========================================
            facecolor color 'white' The facecolor of the slider handle.
            edgecolor color '.75'   The edgecolor of the slider handle.
            size      int   10      The size of the slider handle in points.
            ========= ===== ======= ========================================

            Other values will be transformed as marker{foo} and passed to the
            `~.Line2D` constructor. e.g. ``handle_style = {'style'='x'}`` will
            result in ``markerstyle = 'x'``.

        Notes
        -----
        Additional kwargs are passed on to ``self.poly`` which is the
        `~matplotlib.patches.Polygon` that draws the slider knob.  See the
        `.Polygon` documentation for valid property names (``facecolor``,
        ``edgecolor``, ``alpha``, etc.).
        """
        ...
    def set_val(self, val):  # -> None:
        """
        Set slider value to *val*.

        Parameters
        ----------
        val : float
        """
        ...
    def on_changed(self, func):  # -> int:
        """
        Connect *func* as callback function to changes of the slider value.

        Parameters
        ----------
        func : callable
            Function to call when slider is changed.
            The function must accept a single float as its arguments.

        Returns
        -------
        int
            Connection id (which can be used to disconnect *func*).
        """
        ...

class RangeSlider(SliderBase):
    """
    A slider representing a range of floating point values. Defines the min and
    max of the range via the *val* attribute as a tuple of (min, max).

    Create a slider that defines a range contained within [*valmin*, *valmax*]
    in Axes *ax*. For the slider to remain responsive you must maintain a
    reference to it. Call :meth:`on_changed` to connect to the slider event.

    Attributes
    ----------
    val : tuple of float
        Slider value.
    """

    @_api.make_keyword_only("3.7", name="valinit")
    def __init__(
        self,
        ax,
        label,
        valmin,
        valmax,
        valinit=...,
        valfmt=...,
        closedmin=...,
        closedmax=...,
        dragging=...,
        valstep=...,
        orientation=...,
        track_color=...,
        handle_style=...,
        **kwargs
    ) -> None:
        """
        Parameters
        ----------
        ax : Axes
            The Axes to put the slider in.

        label : str
            Slider label.

        valmin : float
            The minimum value of the slider.

        valmax : float
            The maximum value of the slider.

        valinit : tuple of float or None, default: None
            The initial positions of the slider. If None the initial positions
            will be at the 25th and 75th percentiles of the range.

        valfmt : str, default: None
            %-format string used to format the slider values.  If None, a
            `.ScalarFormatter` is used instead.

        closedmin : bool, default: True
            Whether the slider interval is closed on the bottom.

        closedmax : bool, default: True
            Whether the slider interval is closed on the top.

        dragging : bool, default: True
            If True the slider can be dragged by the mouse.

        valstep : float, default: None
            If given, the slider will snap to multiples of *valstep*.

        orientation : {'horizontal', 'vertical'}, default: 'horizontal'
            The orientation of the slider.

        track_color : color, default: 'lightgrey'
            The color of the background track. The track is accessible for
            further styling via the *track* attribute.

        handle_style : dict
            Properties of the slider handles. Default values are

            ========= ===== ======= =========================================
            Key       Value Default Description
            ========= ===== ======= =========================================
            facecolor color 'white' The facecolor of the slider handles.
            edgecolor color '.75'   The edgecolor of the slider handles.
            size      int   10      The size of the slider handles in points.
            ========= ===== ======= =========================================

            Other values will be transformed as marker{foo} and passed to the
            `~.Line2D` constructor. e.g. ``handle_style = {'style'='x'}`` will
            result in ``markerstyle = 'x'``.

        Notes
        -----
        Additional kwargs are passed on to ``self.poly`` which is the
        `~matplotlib.patches.Polygon` that draws the slider knob.  See the
        `.Polygon` documentation for valid property names (``facecolor``,
        ``edgecolor``, ``alpha``, etc.).
        """
        ...
    def set_min(self, min):  # -> None:
        """
        Set the lower value of the slider to *min*.

        Parameters
        ----------
        min : float
        """
        ...
    def set_max(self, max):  # -> None:
        """
        Set the lower value of the slider to *max*.

        Parameters
        ----------
        max : float
        """
        ...
    def set_val(self, val):  # -> None:
        """
        Set slider value to *val*.

        Parameters
        ----------
        val : tuple or array-like of float
        """
        ...
    def on_changed(self, func):  # -> int:
        """
        Connect *func* as callback function to changes of the slider value.

        Parameters
        ----------
        func : callable
            Function to call when slider is changed. The function
            must accept a 2-tuple of floats as its argument.

        Returns
        -------
        int
            Connection id (which can be used to disconnect *func*).
        """
        ...

class CheckButtons(AxesWidget):
    r"""
    A GUI neutral set of check buttons.

    For the check buttons to remain responsive you must keep a
    reference to this object.

    Connect to the CheckButtons with the `.on_clicked` method.

    Attributes
    ----------
    ax : `~matplotlib.axes.Axes`
        The parent Axes for the widget.

    labels : list of `.Text`

    rectangles : list of `.Rectangle`

    lines : list of (`.Line2D`, `.Line2D`) pairs
        List of lines for the x's in the checkboxes.  These lines exist for
        each box, but have ``set_visible(False)`` when its box is not checked.
    """
    def __init__(
        self,
        ax,
        labels,
        actives=...,
        *,
        useblit=...,
        label_props=...,
        frame_props=...,
        check_props=...
    ) -> None:
        """
        Add check buttons to `matplotlib.axes.Axes` instance *ax*.

        Parameters
        ----------
        ax : `~matplotlib.axes.Axes`
            The parent Axes for the widget.
        labels : list of str
            The labels of the check buttons.
        actives : list of bool, optional
            The initial check states of the buttons. The list must have the
            same length as *labels*. If not given, all buttons are unchecked.
        useblit : bool, default: True
            Use blitting for faster drawing if supported by the backend.
            See the tutorial :doc:`/tutorials/advanced/blitting` for details.

            .. versionadded:: 3.7
        label_props : dict, optional
            Dictionary of `.Text` properties to be used for the labels.

            .. versionadded:: 3.7
        frame_props : dict, optional
            Dictionary of scatter `.Collection` properties to be used for the
            check button frame. Defaults (label font size / 2)**2 size, black
            edgecolor, no facecolor, and 1.0 linewidth.

            .. versionadded:: 3.7
        check_props : dict, optional
            Dictionary of scatter `.Collection` properties to be used for the
            check button check. Defaults to (label font size / 2)**2 size,
            black color, and 1.0 linewidth.

            .. versionadded:: 3.7
        """
        ...
    def set_label_props(self, props):  # -> None:
        """
        Set properties of the `.Text` labels.

        .. versionadded:: 3.7

        Parameters
        ----------
        props : dict
            Dictionary of `.Text` properties to be used for the labels.
        """
        ...
    def set_frame_props(self, props):  # -> None:
        """
        Set properties of the check button frames.

        .. versionadded:: 3.7

        Parameters
        ----------
        props : dict
            Dictionary of `.Collection` properties to be used for the check
            button frames.
        """
        ...
    def set_check_props(self, props):  # -> None:
        """
        Set properties of the check button checks.

        .. versionadded:: 3.7

        Parameters
        ----------
        props : dict
            Dictionary of `.Collection` properties to be used for the check
            button check.
        """
        ...
    def set_active(self, index):  # -> None:
        """
        Toggle (activate or deactivate) a check button by index.

        Callbacks will be triggered if :attr:`eventson` is True.

        Parameters
        ----------
        index : int
            Index of the check button to toggle.

        Raises
        ------
        ValueError
            If *index* is invalid.
        """
        ...
    def get_status(self):  # -> list[bool]:
        """
        Return a list of the status (True/False) of all of the check buttons.
        """
        ...
    def on_clicked(self, func):  # -> int:
        """
        Connect the callback function *func* to button click events.

        Returns a connection id, which can be used to disconnect the callback.
        """
        ...
    def disconnect(self, cid):  # -> None:
        """Remove the observer with connection id *cid*."""
        ...
    @_api.deprecated("3.7", addendum="Any custom property styling may be lost.")
    @property
    def rectangles(self):  # -> list[Rectangle]:
        ...
    @_api.deprecated("3.7", addendum="Any custom property styling may be lost.")
    @property
    def lines(self):  # -> list[Unknown]:
        ...

class TextBox(AxesWidget):
    """
    A GUI neutral text input box.

    For the text box to remain responsive you must keep a reference to it.

    Call `.on_text_change` to be updated whenever the text changes.

    Call `.on_submit` to be updated whenever the user hits enter or
    leaves the text entry field.

    Attributes
    ----------
    ax : `~matplotlib.axes.Axes`
        The parent Axes for the widget.
    label : `~matplotlib.text.Text`

    color : color
        The color of the text box when not hovering.
    hovercolor : color
        The color of the text box when hovering.
    """

    @_api.make_keyword_only("3.7", name="color")
    def __init__(
        self,
        ax,
        label,
        initial=...,
        color=...,
        hovercolor=...,
        label_pad=...,
        textalignment=...,
    ) -> None:
        """
        Parameters
        ----------
        ax : `~matplotlib.axes.Axes`
            The `~.axes.Axes` instance the button will be placed into.
        label : str
            Label for this text box.
        initial : str
            Initial value in the text box.
        color : color
            The color of the box.
        hovercolor : color
            The color of the box when the mouse is over it.
        label_pad : float
            The distance between the label and the right side of the textbox.
        textalignment : {'left', 'center', 'right'}
            The horizontal location of the text.
        """
        ...
    @property
    def text(self): ...
    def set_val(self, val):  # -> None:
        ...
    @_api.delete_parameter("3.7", "x")
    def begin_typing(self, x=...):  # -> None:
        ...
    def stop_typing(self):  # -> None:
        ...
    def on_text_change(self, func):  # -> int:
        """
        When the text changes, call this *func* with event.

        A connection id is returned which can be used to disconnect.
        """
        ...
    def on_submit(self, func):  # -> int:
        """
        When the user hits enter or leaves the submission box, call this
        *func* with event.

        A connection id is returned which can be used to disconnect.
        """
        ...
    def disconnect(self, cid):  # -> None:
        """Remove the observer with connection id *cid*."""
        ...

class RadioButtons(AxesWidget):
    """
    A GUI neutral radio button.

    For the buttons to remain responsive you must keep a reference to this
    object.

    Connect to the RadioButtons with the `.on_clicked` method.

    Attributes
    ----------
    ax : `~matplotlib.axes.Axes`
        The parent Axes for the widget.
    activecolor : color
        The color of the selected button.
    labels : list of `.Text`
        The button labels.
    circles : list of `~.patches.Circle`
        The buttons.
    value_selected : str
        The label text of the currently selected button.
    """

    def __init__(
        self,
        ax,
        labels,
        active=...,
        activecolor=...,
        *,
        useblit=...,
        label_props=...,
        radio_props=...
    ) -> None:
        """
        Add radio buttons to an `~.axes.Axes`.

        Parameters
        ----------
        ax : `~matplotlib.axes.Axes`
            The Axes to add the buttons to.
        labels : list of str
            The button labels.
        active : int
            The index of the initially selected button.
        activecolor : color
            The color of the selected button. The default is ``'blue'`` if not
            specified here or in *radio_props*.
        useblit : bool, default: True
            Use blitting for faster drawing if supported by the backend.
            See the tutorial :doc:`/tutorials/advanced/blitting` for details.

            .. versionadded:: 3.7
        label_props : dict or list of dict, optional
            Dictionary of `.Text` properties to be used for the labels.

            .. versionadded:: 3.7
        radio_props : dict, optional
            Dictionary of scatter `.Collection` properties to be used for the
            radio buttons. Defaults to (label font size / 2)**2 size, black
            edgecolor, and *activecolor* facecolor (when active).

            .. note::
                If a facecolor is supplied in *radio_props*, it will override
                *activecolor*. This may be used to provide an active color per
                button.

            .. versionadded:: 3.7
        """
        ...
    def set_label_props(self, props):  # -> None:
        """
        Set properties of the `.Text` labels.

        .. versionadded:: 3.7

        Parameters
        ----------
        props : dict
            Dictionary of `.Text` properties to be used for the labels.
        """
        ...
    def set_radio_props(self, props):  # -> None:
        """
        Set properties of the `.Text` labels.

        .. versionadded:: 3.7

        Parameters
        ----------
        props : dict
            Dictionary of `.Collection` properties to be used for the radio
            buttons.
        """
        ...
    @property
    def activecolor(self):  # -> str:
        ...
    @activecolor.setter
    def activecolor(self, activecolor):  # -> None:
        ...
    def set_active(self, index):  # -> None:
        """
        Select button with number *index*.

        Callbacks will be triggered if :attr:`eventson` is True.
        """
        ...
    def on_clicked(self, func):  # -> int:
        """
        Connect the callback function *func* to button click events.

        Returns a connection id, which can be used to disconnect the callback.
        """
        ...
    def disconnect(self, cid):  # -> None:
        """Remove the observer with connection id *cid*."""
        ...
    @_api.deprecated("3.7", addendum="Any custom property styling may be lost.")
    @property
    def circles(self):  # -> list[Circle]:
        ...

class SubplotTool(Widget):
    """
    A tool to adjust the subplot params of a `matplotlib.figure.Figure`.
    """

    def __init__(self, targetfig, toolfig) -> None:
        """
        Parameters
        ----------
        targetfig : `.Figure`
            The figure instance to adjust.
        toolfig : `.Figure`
            The figure instance to embed the subplot tool into.
        """
        ...

class Cursor(AxesWidget):
    """
    A crosshair cursor that spans the Axes and moves with mouse cursor.

    For the cursor to remain responsive you must keep a reference to it.

    Parameters
    ----------
    ax : `~matplotlib.axes.Axes`
        The `~.axes.Axes` to attach the cursor to.
    horizOn : bool, default: True
        Whether to draw the horizontal line.
    vertOn : bool, default: True
        Whether to draw the vertical line.
    useblit : bool, default: False
        Use blitting for faster drawing if supported by the backend.
        See the tutorial :doc:`/tutorials/advanced/blitting` for details.

    Other Parameters
    ----------------
    **lineprops
        `.Line2D` properties that control the appearance of the lines.
        See also `~.Axes.axhline`.

    Examples
    --------
    See :doc:`/gallery/widgets/cursor`.
    """

    @_api.make_keyword_only("3.7", "horizOn")
    def __init__(
        self, ax, horizOn=..., vertOn=..., useblit=..., **lineprops
    ) -> None: ...
    def clear(self, event):  # -> None:
        """Internal event handler to clear the cursor."""
        ...
    def onmove(self, event):  # -> None:
        """Internal event handler to draw the cursor when the mouse moves."""
        ...

class MultiCursor(Widget):
    """
    Provide a vertical (default) and/or horizontal line cursor shared between
    multiple Axes.

    For the cursor to remain responsive you must keep a reference to it.

    Parameters
    ----------
    canvas : object
        This parameter is entirely unused and only kept for back-compatibility.

    axes : list of `matplotlib.axes.Axes`
        The `~.axes.Axes` to attach the cursor to.

    useblit : bool, default: True
        Use blitting for faster drawing if supported by the backend.
        See the tutorial :doc:`/tutorials/advanced/blitting`
        for details.

    horizOn : bool, default: False
        Whether to draw the horizontal line.

    vertOn : bool, default: True
        Whether to draw the vertical line.

    Other Parameters
    ----------------
    **lineprops
        `.Line2D` properties that control the appearance of the lines.
        See also `~.Axes.axhline`.

    Examples
    --------
    See :doc:`/gallery/widgets/multicursor`.
    """

    @_api.make_keyword_only("3.6", "useblit")
    def __init__(
        self, canvas, axes, useblit=..., horizOn=..., vertOn=..., **lineprops
    ) -> None: ...

    canvas = ...
    background = ...
    needclear = ...
    def connect(self):  # -> None:
        """Connect events."""
        ...
    def disconnect(self):  # -> None:
        """Disconnect events."""
        ...
    def clear(self, event):  # -> None:
        """Clear the cursor."""
        ...
    def onmove(self, event):  # -> None:
        ...

class _SelectorWidget(AxesWidget):
    def __init__(
        self,
        ax,
        onselect,
        useblit=...,
        button=...,
        state_modifier_keys=...,
        use_data_coordinates=...,
    ) -> None: ...

    state_modifier_keys = ...
    def set_active(self, active):  # -> None:
        ...
    def update_background(self, event):  # -> None:
        """Force an update of the background."""
        ...
    def connect_default_events(self):  # -> None:
        """Connect the major canvas events to methods."""
        ...
    def ignore(self, event):  # -> bool:
        ...
    def update(self):  # -> None:
        """Draw using blit() or draw_idle(), depending on ``self.useblit``."""
        ...
    def press(self, event):  # -> bool:
        """Button press handler and validator."""
        ...
    def release(self, event):  # -> bool:
        """Button release event handler and validator."""
        ...
    def onmove(self, event):  # -> bool:
        """Cursor move event handler and validator."""
        ...
    def on_scroll(self, event):  # -> None:
        """Mouse scroll event handler and validator."""
        ...
    def on_key_press(self, event):  # -> None:
        """Key press event handler and validator for all selection widgets."""
        ...
    def on_key_release(self, event):  # -> None:
        """Key release event handler and validator."""
        ...
    def set_visible(self, visible):  # -> None:
        """Set the visibility of the selector artists."""
        ...
    def get_visible(self):  # -> bool:
        """Get the visibility of the selector artists."""
        ...
    @property
    def visible(self):  # -> bool:
        ...
    @visible.setter
    def visible(self, visible):  # -> None:
        ...
    def clear(self):  # -> None:
        """Clear the selection and set the selector ready to make a new one."""
        ...
    @property
    def artists(self):  # -> Any | tuple[Unknown]:
        """Tuple of the artists of the selector."""
        ...
    def set_props(self, **props):  # -> None:
        """
        Set the properties of the selector artist. See the `props` argument
        in the selector docstring to know which properties are supported.
        """
        ...
    def set_handle_props(self, **handle_props):  # -> None:
        """
        Set the properties of the handles selector artist. See the
        `handle_props` argument in the selector docstring to know which
        properties are supported.
        """
        ...
    def add_state(self, state):  # -> None:
        """
        Add a state to define the widget's behavior. See the
        `state_modifier_keys` parameters for details.

        Parameters
        ----------
        state : str
            Must be a supported state of the selector. See the
            `state_modifier_keys` parameters for details.

        Raises
        ------
        ValueError
            When the state is not supported by the selector.

        """
        ...
    def remove_state(self, state):  # -> None:
        """
        Remove a state to define the widget's behavior. See the
        `state_modifier_keys` parameters for details.

        Parameters
        ----------
        state : str
            Must be a supported state of the selector. See the
            `state_modifier_keys` parameters for details.

        Raises
        ------
        ValueError
            When the state is not supported by the selector.

        """
        ...

class SpanSelector(_SelectorWidget):
    """
    Visually select a min/max range on a single axis and call a function with
    those values.

    To guarantee that the selector remains responsive, keep a reference to it.

    In order to turn off the SpanSelector, set ``span_selector.active`` to
    False.  To turn it back on, set it to True.

    Press and release events triggered at the same coordinates outside the
    selection will clear the selector, except when
    ``ignore_event_outside=True``.

    Parameters
    ----------
    ax : `~matplotlib.axes.Axes`

    onselect : callable
        A callback function that is called after a release event and the
        selection is created, changed or removed.
        It must have the signature::

            def on_select(min: float, max: float) -> Any

    direction : {"horizontal", "vertical"}
        The direction along which to draw the span selector.

    minspan : float, default: 0
        If selection is less than or equal to *minspan*, the selection is
        removed (when already existing) or cancelled.

    useblit : bool, default: False
        If True, use the backend-dependent blitting features for faster
        canvas updates. See the tutorial :doc:`/tutorials/advanced/blitting`
        for details.

    props : dict, optional
        Dictionary of `matplotlib.patches.Patch` properties.
        Default:

            ``dict(facecolor='red', alpha=0.5)``

    onmove_callback : func(min, max), min/max are floats, default: None
        Called on mouse move while the span is being selected.

    span_stays : bool, default: False
        If True, the span stays visible after the mouse is released.
        Deprecated, use *interactive* instead.

    interactive : bool, default: False
        Whether to draw a set of handles that allow interaction with the
        widget after it is drawn.

    button : `.MouseButton` or list of `.MouseButton`, default: all buttons
        The mouse buttons which activate the span selector.

    handle_props : dict, default: None
        Properties of the handle lines at the edges of the span. Only used
        when *interactive* is True. See `matplotlib.lines.Line2D` for valid
        properties.

    grab_range : float, default: 10
        Distance in pixels within which the interactive tool handles can be
        activated.

    state_modifier_keys : dict, optional
        Keyboard modifiers which affect the widget's behavior.  Values
        amend the defaults, which are:

        - "clear": Clear the current shape, default: "escape".

    drag_from_anywhere : bool, default: False
        If `True`, the widget can be moved by clicking anywhere within
        its bounds.

    ignore_event_outside : bool, default: False
        If `True`, the event triggered outside the span selector will be
        ignored.

    snap_values : 1D array-like, optional
        Snap the selector edges to the given values.

    Examples
    --------
    >>> import matplotlib.pyplot as plt
    >>> import matplotlib.widgets as mwidgets
    >>> fig, ax = plt.subplots()
    >>> ax.plot([1, 2, 3], [10, 50, 100])
    >>> def onselect(vmin, vmax):
    ...     print(vmin, vmax)
    >>> span = mwidgets.SpanSelector(ax, onselect, 'horizontal',
    ...                              props=dict(facecolor='blue', alpha=0.5))
    >>> fig.show()

    See also: :doc:`/gallery/widgets/span_selector`
    """

    @_api.make_keyword_only("3.7", name="minspan")
    def __init__(
        self,
        ax,
        onselect,
        direction,
        minspan=...,
        useblit=...,
        props=...,
        onmove_callback=...,
        interactive=...,
        button=...,
        handle_props=...,
        grab_range=...,
        state_modifier_keys=...,
        drag_from_anywhere=...,
        ignore_event_outside=...,
        snap_values=...,
    ) -> None: ...
    def new_axes(self, ax):  # -> None:
        """Set SpanSelector to operate on a new Axes."""
        ...
    def connect_default_events(self):  # -> None:
        ...
    @property
    def direction(self):
        """Direction of the span selector: 'vertical' or 'horizontal'."""
        ...
    @direction.setter
    def direction(self, direction):  # -> None:
        """Set the direction of the span selector."""
        ...
    @property
    def extents(self):  # -> tuple[Unknown, Unknown]:
        """Return extents of the span selector."""
        ...
    @extents.setter
    def extents(self, extents):  # -> None:
        ...

class ToolLineHandles:
    """
    Control handles for canvas tools.

    Parameters
    ----------
    ax : `~matplotlib.axes.Axes`
        Matplotlib Axes where tool handles are displayed.
    positions : 1D array
        Positions of handles in data coordinates.
    direction : {"horizontal", "vertical"}
        Direction of handles, either 'vertical' or 'horizontal'
    line_props : dict, optional
        Additional line properties. See `matplotlib.lines.Line2D`.
    useblit : bool, default: True
        Whether to use blitting for faster drawing (if supported by the
        backend). See the tutorial :doc:`/tutorials/advanced/blitting`
        for details.
    """

    @_api.make_keyword_only("3.7", "line_props")
    def __init__(
        self, ax, positions, direction, line_props=..., useblit=...
    ) -> None: ...
    @property
    def artists(self):  # -> tuple[Unknown, ...]:
        ...
    @property
    def positions(self):  # -> list[Any]:
        """Positions of the handle in data coordinates."""
        ...
    @property
    def direction(self):  # -> Unknown:
        """Direction of the handle: 'vertical' or 'horizontal'."""
        ...
    def set_data(self, positions):  # -> None:
        """
        Set x- or y-positions of handles, depending on if the lines are
        vertical or horizontal.

        Parameters
        ----------
        positions : tuple of length 2
            Set the positions of the handle in data coordinates
        """
        ...
    def set_visible(self, value):  # -> None:
        """Set the visibility state of the handles artist."""
        ...
    def set_animated(self, value):  # -> None:
        """Set the animated state of the handles artist."""
        ...
    def remove(self):  # -> None:
        """Remove the handles artist from the figure."""
        ...
    def closest(self, x, y):  # -> tuple[intp, Unknown]:
        """
        Return index and pixel distance to closest handle.

        Parameters
        ----------
        x, y : float
            x, y position from which the distance will be calculated to
            determinate the closest handle

        Returns
        -------
        index, distance : index of the handle and its distance from
            position x, y
        """
        ...

class ToolHandles:
    """
    Control handles for canvas tools.

    Parameters
    ----------
    ax : `~matplotlib.axes.Axes`
        Matplotlib Axes where tool handles are displayed.
    x, y : 1D arrays
        Coordinates of control handles.
    marker : str, default: 'o'
        Shape of marker used to display handle. See `matplotlib.pyplot.plot`.
    marker_props : dict, optional
        Additional marker properties. See `matplotlib.lines.Line2D`.
    useblit : bool, default: True
        Whether to use blitting for faster drawing (if supported by the
        backend). See the tutorial :doc:`/tutorials/advanced/blitting`
        for details.
    """

    @_api.make_keyword_only("3.7", "marker")
    def __init__(self, ax, x, y, marker=..., marker_props=..., useblit=...) -> None: ...
    @property
    def x(self):  # -> NDArray[Unknown] | list[Unknown] | Iterable[Any] | None:
        ...
    @property
    def y(self):  # -> NDArray[Unknown] | list[Unknown] | Iterable[Any] | None:
        ...
    @property
    def artists(self):  # -> tuple[Line2D]:
        ...
    def set_data(self, pts, y=...):  # -> None:
        """Set x and y positions of handles."""
        ...
    def set_visible(self, val):  # -> None:
        ...
    def set_animated(self, val):  # -> None:
        ...
    def closest(self, x, y):  # -> tuple[intp, Any]:
        """Return index and pixel distance to closest index."""
        ...

_RECTANGLESELECTOR_PARAMETERS_DOCSTRING = ...

@_docstring.Substitution(
    _RECTANGLESELECTOR_PARAMETERS_DOCSTRING.replace("__ARTIST_NAME__", "rectangle")
)
class RectangleSelector(_SelectorWidget):
    """
    Select a rectangular region of an Axes.

    For the cursor to remain responsive you must keep a reference to it.

    Press and release events triggered at the same coordinates outside the
    selection will clear the selector, except when
    ``ignore_event_outside=True``.

    %s

    Examples
    --------
    >>> import matplotlib.pyplot as plt
    >>> import matplotlib.widgets as mwidgets
    >>> fig, ax = plt.subplots()
    >>> ax.plot([1, 2, 3], [10, 50, 100])
    >>> def onselect(eclick, erelease):
    ...     print(eclick.xdata, eclick.ydata)
    ...     print(erelease.xdata, erelease.ydata)
    >>> props = dict(facecolor='blue', alpha=0.5)
    >>> rect = mwidgets.RectangleSelector(ax, onselect, interactive=True,
    ...                                   props=props)
    >>> fig.show()
    >>> rect.add_state('square')

    See also: :doc:`/gallery/widgets/rectangle_selector`
    """

    def __init__(
        self,
        ax,
        onselect,
        *,
        minspanx=...,
        minspany=...,
        useblit=...,
        props=...,
        spancoords=...,
        button=...,
        grab_range=...,
        handle_props=...,
        interactive=...,
        state_modifier_keys=...,
        drag_from_anywhere=...,
        ignore_event_outside=...,
        use_data_coordinates=...
    ) -> None: ...
    @property
    def corners(self):  # -> tuple[Unknown, Unknown]:
        """
        Corners of rectangle in data coordinates from lower left,
        moving clockwise.
        """
        ...
    @property
    def edge_centers(self):  # -> tuple[Unknown, Unknown]:
        """
        Midpoint of rectangle edges in data coordinates from left,
        moving anti-clockwise.
        """
        ...
    @property
    def center(self):  # -> tuple[Unknown, Unknown]:
        """Center of rectangle in data coordinates."""
        ...
    @property
    def extents(self):  # -> tuple[Unknown, Unknown, Unknown, Unknown]:
        """
        Return (xmin, xmax, ymin, ymax) in data coordinates as defined by the
        bounding box before rotation.
        """
        ...
    @extents.setter
    def extents(self, extents):  # -> None:
        ...
    @property
    def rotation(self):  # -> Any:
        """
        Rotation in degree in interval [-45°, 45°]. The rotation is limited in
        range to keep the implementation simple.
        """
        ...
    @rotation.setter
    def rotation(self, value):  # -> None:
        ...
    @property
    def geometry(self):  # -> NDArray[Unknown]:
        """
        Return an array of shape (2, 5) containing the
        x (``RectangleSelector.geometry[1, :]``) and
        y (``RectangleSelector.geometry[0, :]``) data coordinates of the four
        corners of the rectangle starting and ending in the top left corner.
        """
        ...

@_docstring.Substitution(
    _RECTANGLESELECTOR_PARAMETERS_DOCSTRING.replace("__ARTIST_NAME__", "ellipse")
)
class EllipseSelector(RectangleSelector):
    """
    Select an elliptical region of an Axes.

    For the cursor to remain responsive you must keep a reference to it.

    Press and release events triggered at the same coordinates outside the
    selection will clear the selector, except when
    ``ignore_event_outside=True``.

    %s

    Examples
    --------
    :doc:`/gallery/widgets/rectangle_selector`
    """

    ...

class LassoSelector(_SelectorWidget):
    """
    Selection curve of an arbitrary shape.

    For the selector to remain responsive you must keep a reference to it.

    The selected path can be used in conjunction with `~.Path.contains_point`
    to select data points from an image.

    In contrast to `Lasso`, `LassoSelector` is written with an interface
    similar to `RectangleSelector` and `SpanSelector`, and will continue to
    interact with the Axes until disconnected.

    Example usage::

        ax = plt.subplot()
        ax.plot(x, y)

        def onselect(verts):
            print(verts)
        lasso = LassoSelector(ax, onselect)

    Parameters
    ----------
    ax : `~matplotlib.axes.Axes`
        The parent Axes for the widget.
    onselect : function
        Whenever the lasso is released, the *onselect* function is called and
        passed the vertices of the selected path.
    useblit : bool, default: True
        Whether to use blitting for faster drawing (if supported by the
        backend). See the tutorial :doc:`/tutorials/advanced/blitting`
        for details.
    props : dict, optional
        Properties with which the line is drawn, see `matplotlib.lines.Line2D`
        for valid properties. Default values are defined in ``mpl.rcParams``.
    button : `.MouseButton` or list of `.MouseButton`, optional
        The mouse buttons used for rectangle selection.  Default is ``None``,
        which corresponds to all buttons.
    """

    @_api.make_keyword_only("3.7", name="useblit")
    def __init__(self, ax, onselect, useblit=..., props=..., button=...) -> None: ...

class PolygonSelector(_SelectorWidget):
    """
    Select a polygon region of an Axes.

    Place vertices with each mouse click, and make the selection by completing
    the polygon (clicking on the first vertex). Once drawn individual vertices
    can be moved by clicking and dragging with the left mouse button, or
    removed by clicking the right mouse button.

    In addition, the following modifier keys can be used:

    - Hold *ctrl* and click and drag a vertex to reposition it before the
      polygon has been completed.
    - Hold the *shift* key and click and drag anywhere in the Axes to move
      all vertices.
    - Press the *esc* key to start a new polygon.

    For the selector to remain responsive you must keep a reference to it.

    Parameters
    ----------
    ax : `~matplotlib.axes.Axes`
        The parent Axes for the widget.

    onselect : function
        When a polygon is completed or modified after completion,
        the *onselect* function is called and passed a list of the vertices as
        ``(xdata, ydata)`` tuples.

    useblit : bool, default: False
        Whether to use blitting for faster drawing (if supported by the
        backend). See the tutorial :doc:`/tutorials/advanced/blitting`
        for details.

    props : dict, optional
        Properties with which the line is drawn, see `matplotlib.lines.Line2D`
        for valid properties.
        Default:

            ``dict(color='k', linestyle='-', linewidth=2, alpha=0.5)``

    handle_props : dict, optional
        Artist properties for the markers drawn at the vertices of the polygon.
        See the marker arguments in `matplotlib.lines.Line2D` for valid
        properties.  Default values are defined in ``mpl.rcParams`` except for
        the default value of ``markeredgecolor`` which will be the same as the
        ``color`` property in *props*.

    grab_range : float, default: 10
        A vertex is selected (to complete the polygon or to move a vertex) if
        the mouse click is within *grab_range* pixels of the vertex.

    draw_bounding_box : bool, optional
        If `True`, a bounding box will be drawn around the polygon selector
        once it is complete. This box can be used to move and resize the
        selector.

    box_handle_props : dict, optional
        Properties to set for the box handles. See the documentation for the
        *handle_props* argument to `RectangleSelector` for more info.

    box_props : dict, optional
        Properties to set for the box. See the documentation for the *props*
        argument to `RectangleSelector` for more info.

    Examples
    --------
    :doc:`/gallery/widgets/polygon_selector_simple`
    :doc:`/gallery/widgets/polygon_selector_demo`

    Notes
    -----
    If only one point remains after removing points, the selector reverts to an
    incomplete state and you can start drawing a new polygon from the existing
    point.
    """

    @_api.make_keyword_only("3.7", name="useblit")
    def __init__(
        self,
        ax,
        onselect,
        useblit=...,
        props=...,
        handle_props=...,
        grab_range=...,
        *,
        draw_bounding_box=...,
        box_handle_props=...,
        box_props=...
    ) -> None: ...
    def onmove(self, event):  # -> bool:
        """Cursor move event handler and validator."""
        ...
    @property
    def verts(
        self,
    ):  # -> list[tuple[Literal[0], Literal[0]]] | list[tuple[Unknown, Unknown]] | list[Unknown]:
        """The polygon vertices, as a list of ``(x, y)`` pairs."""
        ...
    @verts.setter
    def verts(self, xys):  # -> None:
        """
        Set the polygon vertices.

        This will remove any preexisting vertices, creating a complete polygon
        with the new vertices.
        """
        ...

class Lasso(AxesWidget):
    """
    Selection curve of an arbitrary shape.

    The selected path can be used in conjunction with
    `~matplotlib.path.Path.contains_point` to select data points from an image.

    Unlike `LassoSelector`, this must be initialized with a starting
    point *xy*, and the `Lasso` events are destroyed upon release.

    Parameters
    ----------
    ax : `~matplotlib.axes.Axes`
        The parent Axes for the widget.
    xy : (float, float)
        Coordinates of the start of the lasso.
    callback : callable
        Whenever the lasso is released, the *callback* function is called and
        passed the vertices of the selected path.
    useblit : bool, default: True
        Whether to use blitting for faster drawing (if supported by the
        backend). See the tutorial :doc:`/tutorials/advanced/blitting`
        for details.
    """

    @_api.make_keyword_only("3.7", name="useblit")
    def __init__(self, ax, xy, callback, useblit=...) -> None: ...
    def onrelease(self, event):  # -> None:
        ...
    def onmove(self, event):  # -> None:
        ...
